### ISSUE TITLE
Access to the unsolved ODEProblem / DAEProblem / BVPProblem

### ISSUE THREAD

**Issue by nathanaelbosch** [ai4energy/OptControl.jl#6]
As I understand OptControl.jl, one way to solve the specified optimal control problem is via DifferentialEquations.jl. Is there an option to  access the generated ODEProblem / DAEProblem / BVPProblem, e.g. to choose a different solver or solver parameters? For me personally it would be very convenient if the API would be split into "generating the problem" and "solving the problem", such that I could have more control over the latter.

**Comment by jake484** [comment]
That's right. Now, OptControl.jl can only generate BVPProblem if via DifferentialEquations.jl. Actually, this package are designed to *write code automatically * and  *generate a template to solve optimal control via DifferentialEquations.jl and JuMP.jl*, and it doesn't deal with struct. The form of generated problem is a Julia script(a string). Therefore, when solving problem, the function just run `eval(Meta.parse())`. If you want to choose different solver or solver parameters, you can do it in generated script. Pass a string as the name of script to `writeFilePath` and then you can see the script in folder. I will consider add more interface to choose solver parameters. Thank for your advice.

**Comment by nathanaelbosch** [comment]
Thanks for the reply, I was not aware of the `writeFilePath` option. That does indeed give me control over what to do with the genereated problem and resolves my question. Thanks again, and nice work on the package!
